### ISSUE TITLE
More issues on Windows 8.1 64 bit

### ISSUE THREAD

**Issue by korgano** [dhavard/ValkyrieEdit#2]
I'm having more issues, and I'm starting to think it might have to do with my OS and/or not having VS. This was tested on the two latest versions of the binaries. Here's what I got:
-ValkyrieEdit.exe will auto-close upon completion of CSV extraction from the MXE file.
(This is contrary to the expected behavior shown in your demo video)
-Reopening ValkyrieEdit and typing in the Sync command (*.mxe -S) will do nothing, aside from crashing the program and generating a target.txt file.
-Right clicking in the ValkyrieEdit.exe window will do nothing, but right clicking in Command Prompt (opened through Windows Search) brings up Copy/Paste prompts.

Right now, all I can do is extract CSVs from MXEs. I have no ability to sync the modded files I have made with the files inside the relevant MXE, so I can't test them at all.

**Comment by dhavard** [comment]
I have a couple of different OS's available to me, but not any W8 versions sorry.
- ValkyrieEdit.exe currently only does one operation per run, so if you execute it simply by clicking on it, yes it will auto close after its done doing whatever you want to do. Eventually, I will probably change it to have an input loop... especially once it has more functionality such as the .mtp editing that I'm adding at the moment. 
- I think what is happening here is you are launching ValkyrieEdit, and then, when it prompts you to enter a filename, you are trying to also tell it to do a sync. The sync mode (or any of the mode changes) has to be an argument provided at launch time. Try this:

1 Open a command prompt (reference http://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/)
2 Navigate to wherever you have ValkyrieEdit...

> cd C:\Users\MyUser\Downloads\ValkyrieEdit\

3 Run ValkyrieEdit in sync mode

> ValkyrieEdit.exe -s

4 It will prompt you to provide a file while running ValkyrieEdit.exe

> /path/to/my/file/game_info_game_param.mxe

5 It will read all the associated CSVs and then, if there are any changes found, update the mxe and generate a backup.
- Good to know that right clicking, if ValkyrieEdit.exe is launched directly, does not allow pasting. Might be a windows 8 specific behavior. I don't seem to have this problem on windows 7, 10, vista, server 2008,  or server 2003 (all of which I tested this morning). I suggest using a bat file.

1 Create a text file and put the following in it:

> VakyrieEdit.exe -s 
> pause

2 Rename that text file (including extension) from "New Text Document.txt" to "save.bat"
3 click on it to run in save mode.
4 this should allow pasting. if it doesn't you can also simply just add the file argument to the bat file:

> VakyrieEdit.exe -s /path/to/my/mxe/game_info_game_param.mxe
> pause

### Looks like user error, but let me know if these suggestions help. If they do, I'll add some "default" set of bat files to the binaries section to help people along a little more...
